apiVersion: v1
kind: ConfigMap
metadata:
  name: habithub-config
  namespace: habithub
data:
  DB_HOST: "habithub-db"
  DB_PORT: "5432"
  DB_NAME: "habithub"
  DB_USER: "habithub"
  PORT: "3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: habithub-secret
  namespace: habithub
type: Opaque
stringData:
  DB_PASSWORD: "habithub123"
  POSTGRES_PASSWORD: "habithub123"
